trigger:
  branches:
    include:
      - feature/*
      - main

pool: Default

steps:

- checkout: self

- script: |
    echo "Repository downloaded successfully"
    pwd
    ls -R
  displayName: "Checkout Repository"